apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ibm-sam-openldap
  annotations:
    openshift.io/display-name: IBM SAM OpenLDAP
    iconClass: icon-sso
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-ldaplib
    labels:
      app: ${APP_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-ldapslapd
    labels:
      app: ${APP_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-ldapsecauthority
    labels:
      app: ${APP_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-domain: '{.data[''domain'']}'
      template.openshift.io/expose-admin_password: '{.data[''admin-password'']}'
      template.openshift.io/expose-config_password: '{.data[''config-password'']}'
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  stringData:
    domain: ${DOMAIN}
    admin-password: ${ADMIN_PW}
    config-password: ${CONFIG_PW}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: null
    generation: 3
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${APP_NAME}
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
      spec:
        serviceAccountName: ${SERVICE_ACCOUNT}
        containers:
        - args:
          - --copy-service
          env:
          - name: LDAP_DOMAIN
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}
                key: domain
          - name: LDAP_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}
                key: admin-password
          - name: LDAP_CONFIG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}
                key: config-password
          image: docker.io/ibmcom/isam-openldap:${LDAP_VERSION}
          imagePullPolicy: IfNotPresent
          name: ${APP_NAME}
          ports:
          - containerPort: 636
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/ldap
            name: ${APP_NAME}-ldaplib
          - mountPath: /etc/ldap/slapd.d
            name: ${APP_NAME}-ldapslapd
          - mountPath: /var/lib/ldap.secAuthority
            name: ${APP_NAME}-ldapsecauthority
          - mountPath: /container/service/slapd/assets/certs
            name: ${APP_NAME}-keys
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${APP_NAME}-ldapslapd
          persistentVolumeClaim:
            claimName: ${APP_NAME}-ldapslapd
        - name: ${APP_NAME}-ldaplib
          persistentVolumeClaim:
            claimName: ${APP_NAME}-ldaplib
        - name: ${APP_NAME}-ldapsecauthority
          persistentVolumeClaim:
            claimName: ${APP_NAME}-ldapsecauthority
        - name: ${APP_NAME}-keys
          secret:
            defaultMode: 420
            secretName: ${KEY_SECRET}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: ldaps
      port: 636
      protocol: TCP
      targetPort: 636
    selector:
      app: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
  - description: Application Name
    name: APP_NAME
    value: openldap
  - description: ISAM Version to be deployed
    name: LDAP_VERSION
    value: 9.0.7.0
  - description: Domain
    name: DOMAIN
    value: ibm.com
  - description: Administrator Password
    name: ADMIN_PW
    from: '[a-zA-Z0-9]{16}'
    generate: expression
  - description: Config Password
    name: CONFIG_PW
    from: '[a-zA-Z0-9]{16}'
    generate: expression
  - description: Secret containing keys
    name: KEY_SECRET
    value: openldap-keys
  - description: Service Account
    name: SERVICE_ACCOUNT
    value: openldap
