apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ibm-sam-reverse-proxy
  annotations:
    openshift.io/display-name: IBM SAM Reverse Proxy
    iconClass: icon-sso
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: null
    generation: 1
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: ${APP_NAME}
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
      spec:
        serviceAccountName: ${SERVICE_ACCOUNT}
        securityContext:
          runAsNonRoot: true
          runAsUser:    6000
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - ${APP_NAME}
                topologyKey: kubernetes.io/hostname
        containers:
        - env:
          - name: SERVICE
            value: webseal
          - name: INSTANCE
            value: ${INSTANCE_NAME}
          - name: CONTAINER_TIMEZONE
            value: ${TIMEZONE}
          - name: AUTO_RELOAD_FREQUENCY
            value: "5"
          - name: CONFIG_SERVICE_URL
            value: https://${CONFIG_SERVICE}:9443/shared_volume
          - name: CONFIG_SERVICE_USER_NAME
            value: cfgsvc
          - name: CONFIG_SERVICE_USER_PWD
            valueFrom:
              secretKeyRef:
                key: cfgsvcpw
                name: ${CFGSVC_SECRET}
          image: docker.io/store/ibmcorp/isam:${ISAM_VERSION}
          imagePullPolicy: IfNotPresent
          name: ${APP_NAME}
          ports:
          - containerPort: 443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            exec:
              command:
              - /sbin/health_check.sh
              - livenessProbe
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
              - /sbin/health_check.sh
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
          volumeMounts:
          - mountPath: /var/application.logs
            name: ${APP_NAME}-logs
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: ${PULL_SECRET}
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ${APP_NAME}-logs
          emptyDir: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    host: ${DNS_NAME}
    port:
      targetPort: ${APP_NAME}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: passthrough
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: ${APP_NAME}
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: ${APP_NAME}
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: NodePort
  status:
    loadBalancer: {}
parameters:
  - description: ISAM Version to be deployed
    name: ISAM_VERSION
    value: 9.0.7.0_IF1
  - description: Application Name
    name: APP_NAME
    value: isamwrprp1
  - description: Instance name
    name: INSTANCE_NAME
    value: rp1
  - description: Fully Qualified DNS Name for Route
    name: DNS_NAME
    value: www.iamlab.ibm.com
  - description: Config Service Name
    name: CONFIG_SERVICE
    value: isamconfig
  - description: Secret for Config Service Password
    name: CFGSVC_SECRET
    value: configreader
  - description: Secret for Image Pull
    name: PULL_SECRET
    value: dockerlogin
  - description: Timezone for container
    name: TIMEZONE
    value: Europe/London
  - description: Service Account
    name: SERVICE_ACCOUNT
    value: isam
