# 
# The minimum security context constraints which are required to run
# the ISAM container.  We cannot use the 'restricted' security
# constraint as we need additional capabilities which would otherwise
# be denied to the container.  The 'anyuid' security constraint may 
# be used, but it allows additional capabilities which are not 
# required by the container.
#

kind: SecurityContextConstraints
apiVersion: v1

# The name and description for the security context constraint to be
# created.
metadata:
  name: isam-scc
  annotations:
    kubernetes.io/description: The isam SCC allows the container to run
                 as any non-root user.

# The following capabilities are not required.
allowHostDirVolumePlugin: false
allowHostIPC:             false
allowHostNetwork:         false
allowHostPID:             false
allowHostPorts:           false
allowPrivilegedContainer: false
readOnlyRootFilesystem:   false

# The priority is set to '10', otherwise the security constraint does
# not take affect when applied to a service account.
priority: 10

# The ISAM container needs to be run as a 'custom' user, but does 
# not need to run as the root user.
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny

# The following volumes are required by the ISAM container.
volumes:
- configMap
- emptyDir
- projected
- secret
- downwardAPI
- persistentVolumeClaim

# By default we drop all capabilities and then only add back in the 
# capabilities which are required by the ISAM container.
requiredDropCapabilities:
- ALL

# The capabilities which are required by the ISAM container.
allowedCapabilities:
- CHOWN
- DAC_OVERRIDE
- FOWNER
- KILL
- NET_BIND_SERVICE
- SETFCAP
- SETGID
- SETUID

defaultAddCapabilities:
- CHOWN
- DAC_OVERRIDE
- FOWNER
- KILL
- NET_BIND_SERVICE
- SETFCAP
- SETGID
- SETUID

---
#
# Security Context Constraint for OpenLDAP.
# Allows OpenLDAP to run as root
#

kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: anyuid provides all features of the restricted SCC
      but allows users to run with any UID and any GID.
  creationTimestamp: null
  name: openldap-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedFlexVolumes: null
apiVersion: v1
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret

