apiVersion: v1
entries:
  iamlab-sam:
  - apiVersion: v1
    appVersion: 9.0.7.1_IF4
    created: "2020-03-24T10:18:09.630903Z"
    dependencies:
    - alias: sch
      name: ibm-sch
      repository: '@sch'
      version: 1.2.15
    - alias: isamconfig
      name: ibm-sam-config
      repository: file://charts/ibm-sam-config
      version: 1.0.0
    - alias: isamwrp
      name: ibm-sam-wrp
      repository: file://charts/ibm-sam-wrp
      version: 1.0.0
    - alias: isamruntime
      name: ibm-sam-runtime
      repository: file://charts/ibm-sam-runtime
      version: 1.0.0
    - alias: isamdsc
      name: ibm-sam-dsc
      repository: file://charts/ibm-sam-dsc
      version: 1.0.0
    - alias: isampostgresql
      name: ibm-sam-postgresql
      repository: file://charts/ibm-sam-postgresql
      version: 1.0.0
    - alias: isamopenldap
      name: ibm-sam-openldap
      repository: file://charts/ibm-sam-openldap
      version: 1.0.0
    description: IBM Security Access Manager provides a simplified access management
      solution.
    digest: 96af66a598d2845cda852e80c4fd54b71cd7db5f2a50e9e89b935d1198aeb76d
    home: https://hub.docker.com/r/ibmcom/isam
    icon: https://d1q6f0aelx0por.cloudfront.net/product-logos/32925feb-af2b-4b4c-8276-def2a031ed31-artwork2x.png
    keywords:
    - isam
    - amd64
    - Security
    - Limited
    maintainers:
    - name: IBM Security Access Manager
    name: iamlab-sam
    sources:
    - https://github.com/jonpharry/isamdocker/tree/master/studentfiles/container-install/helm/charts
    urls:
    - iamlab-sam-0.7.1.tgz
    version: 0.7.1
generated: "2020-03-24T10:18:09.619005Z"
