 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: iamlab-isamconfig
   annotations:
     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
 spec:
  tls:
  - hosts:
    - isam.iamlab.ibm.com
  rules:
  - host: isam.iamlab.ibm.com
    http:
      paths:
      - path: /
        backend:
          serviceName: iamlab-isamconfig
          servicePort: 9443
