apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        rewrite name isamconfig iamlab-isamconfig.default.svc.cluster.local
        rewrite name isamwrprp1 iamlab-isamwrp-rp1.default.svc.cluster.local
        rewrite name postgresql iamlab-isampostgresql.default.svc.cluster.local
        rewrite name isamruntime iamlab-isamruntime.default.svc.cluster.local
        rewrite name isamdsc iamlab-isamdsc-primary.default.svc.cluster.local
        rewrite name openldap iamlab-isamopenldap.default.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
