
#
# This file contains the default values used by the helm chart installation.
#

###############################################################################
# Global configuration which is available to all sub-charts

global:
  # Common image variables
  image:
    repository:   store/ibmcorp/isam:9.0.7.1_IF2
    dbrepository: ibmcom/isam-postgresql:9.0.7.0
    ldaprepository: ibmcom/isam-openldap:9.0.7.0
    pullPolicy:   IfNotPresent

  # Image credentials.
  imageCredentials:
    dockerSecret: "dockerlogin"

  # Container configuration.
  container:
    snapshot:            ""
    fixpacks:            ""
    adminSecret:         "helm-samadmin"
    autoReloadInterval: 10

  # Persistence Storage
  persistence:
    enabled:                true
    useDynamicProvisioning: true

###############################################################################
# Configuration container variables.

isamconfig:

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 2Gi
      cpu:    2000m

  # Service Configuration.
  service:
    type: NodePort

  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        5Gi

###############################################################################
# Web Reverse Proxy container variables.

isamwrp:

  # Container configuration.
  container:
    instances:
      - rp1
    replicas:  1

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  # Service Configuration.
  service:
    type: NodePort


###############################################################################
# Runtime container variables.

isamruntime:

  # Container configuration.
  container:
    enabled:  true
    replicas: 1

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 500Mi
      cpu:    500m
    limits:
      memory: 2Gi
      cpu:    2000m

###############################################################################
# DSC container variables.

isamdsc:

  # Container configuration.
  container:
    enabled:    true
    useReplica: false

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

###############################################################################
# postgresql container variables.

isampostgresql:

  # Container configuration.
  container:
    enabled: true
    keySecretName: "postgresql-keys"

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        5Gi

###############################################################################
# openldap container variables.

isamopenldap:

  # Container configuration.
  container:
    enabled: true
    keySecretName: "openldap-keys"

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        5Gi
